version: "3"
services:
    pyhttp-svc:
        image: pyhttp
        deploy:
            replicas: 3
        ports:
            - 8080:8000

# docker service ls
# ID                  NAME                      MODE                REPLICAS            IMAGE               PORTS
# xz96q6hv11sh        pyhttp-stack_pyhttp-svc   replicated          3/3                 pyhttp:latest       *:8080->8000/tcp

# docker ps
# CONTAINER ID        IMAGE               COMMAND                  CREATED                  STATUS              PORTS               NAMES
# 4efa2afa809a        pyhttp:latest       "python3 -m http.ser…"   Less than a second ago   Up 1 second                             pyhttp-stack_pyhttp-svc.1.0dxv8bmeyw8enzz8v6339t3z1
# 0b255c9fbae1        pyhttp:latest       "python3 -m http.ser…"   Less than a second ago   Up 1 second                             pyhttp-stack_pyhttp-svc.3.y8j6tkj0c6sz44su9rzrk7ucr
# c64deb5f194d        pyhttp:latest       "python3 -m http.ser…"   Less than a second ago   Up 3 seconds                            pyhttp-stack_pyhttp-svc.2.ulvy8ku7ap7dibgmwf39v7c0p


# curl http://localhost:8080/etc/hostname
# 0b255c9fbae1

# curl http://localhost:8080/etc/hostname
# 4efa2afa809a

# curl http://localhost:8080/etc/hostname
# c64deb5f194d

# curl http://localhost:8080/etc/hostname
# 0b255c9fbae1

# curl http://localhost:8080/etc/hostname
# 4efa2afa809a

# curl http://localhost:8080/etc/hostname
# c64deb5f194d

# Note round-robin load balancing in the output above


# docker exec -it 0b255c9fbae1 netstat -t
# Active Internet connections (w/o servers)
# Proto Recv-Q Send-Q Local Address           Foreign Address         State       
# tcp        0      0 10.255.0.29:8000        10.255.0.2:43214        TIME_WAIT   
# tcp        0      0 10.255.0.29:8000        10.255.0.2:43208        TIME_WAIT   
# tcp        0      0 10.255.0.29:8000        10.255.0.2:43220        TIME_WAIT   

# docker exec -it 4efa2afa809a netstat -t
# Active Internet connections (w/o servers)
# Proto Recv-Q Send-Q Local Address           Foreign Address         State       
# tcp        0      0 10.255.0.30:8000        10.255.0.2:43216        TIME_WAIT   
# tcp        0      0 10.255.0.30:8000        10.255.0.2:43222        TIME_WAIT   
# tcp        0      0 10.255.0.30:8000        10.255.0.2:43210        TIME_WAIT   

# docker exec -it c64deb5f194d netstat -t
# Active Internet connections (w/o servers)
# Proto Recv-Q Send-Q Local Address           Foreign Address         State       
# tcp        0      0 10.255.0.28:8000        10.255.0.2:43218        TIME_WAIT   
# tcp        0      0 10.255.0.28:8000        10.255.0.2:43224        TIME_WAIT   
# tcp        0      0 10.255.0.28:8000        10.255.0.2:43212        TIME_WAIT

# All replica containers receive connection from a single IP address
# (10.255.0.2 in this case) when we visit the Python HTTP server running
# on the service.
